"""Speech-to-text benchmarking: accuracy and latency metrics, and a clip runner."""

from .metrics import (
    ErrorCounts,
    aggregate,
    cer,
    edit_counts,
    has_repetition,
    is_boilerplate,
    is_hallucination,
    latency_stats,
    percentile,
    real_time_factor,
    wer,
)
from .runner import (
    BenchError,
    BenchReport,
    Clip,
    ClipResult,
    ProviderResult,
    ProviderSpec,
    decode_audio,
    discover_clips,
    parse_provider_specs,
    read_reference,
    run_bench,
    split_pcm,
    write_report,
)

__all__ = [
    "BenchError",
    "BenchReport",
    "Clip",
    "ClipResult",
    "ErrorCounts",
    "ProviderResult",
    "ProviderSpec",
    "aggregate",
    "cer",
    "decode_audio",
    "discover_clips",
    "edit_counts",
    "has_repetition",
    "is_boilerplate",
    "is_hallucination",
    "latency_stats",
    "parse_provider_specs",
    "percentile",
    "read_reference",
    "real_time_factor",
    "run_bench",
    "split_pcm",
    "wer",
    "write_report",
]
